### ISSUE TITLE
_tkinter.TclError

### ISSUE THREAD

**Issue by carristoner** [taikoma/TennisVideoAnalysis#10]
Hi! I was having an issue running the code and I wasn't sure how to fix it. I tried my best to no avail and wanted to know if you had any ideas. Each time I run the code I get a _tkinter.TclError at the end regarding pre100.png. Thank you!
![image](https://user-images.githubusercontent.com/107444860/173466695-277310b1-7bac-429e-b641-98cbad671ca1.png)
![image](https://user-images.githubusercontent.com/107444860/173466738-517f1853-c248-4f06-a397-4b5140cd17fb.png)

**Comment by taikoma** [comment]
It was because the design file was missing.
Now that I've uploaded the design files on github, could you do a git clone again?
![image](https://user-images.githubusercontent.com/7829080/173603029-b83fdf16-2a69-41b3-a0f1-be028c05f7c2.png)

**Comment by carristoner** [comment]
I cloned it and its running now. Thank you so much!
